name: Build Custom OS Images
on:
  schedule:
    - cron: '0 0 * * 0' # weekly build
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'justfile'
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipes/gaming-desktop.yml
          - recipes/server.yml
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Clean Signing Key
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
        run: |
          CLEAN_KEY=$(echo "$SIGNING_SECRET" | tr -d '\r')
          echo "CLEAN_SIGNING_KEY<<EOF" >> $GITHUB_ENV
          echo "$CLEAN_KEY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ env.CLEAN_SIGNING_KEY }}
          registry_token: ${{ github.token }}
        env:
          COSIGN_PASSWORD: ""
